# Generated by Django 5.2.5 on 2025-08-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('type', models.CharField(choices=[('CITY', 'City'), ('SEAPORT', 'Sea Port'), ('AIRPORT', 'Airport'), ('JETTY', 'Jetty')], max_length=10)),
            ],
            options={
                'ordering': ['type', 'name'],
                'unique_together': {('code', 'type')},
            },
        ),
    ]
