# Generated by Django 5.2.5 on 2025-08-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField()),
                ('origin', models.CharField(max_length=100)),
                ('cargo_desc', models.CharField(blank=True, max_length=255)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('incoterms', models.CharField(blank=True, max_length=10)),
                ('transit_time_days', models.CharField(blank=True, max_length=30)),
                ('schedule', models.CharField(blank=True, max_length=50)),
                ('extra_notes', models.TextField(blank=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='sales.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('FREIGHT', 'FREIGHT'), ('ORIGIN', 'ORIGIN'), ('DEST', 'DEST'), ('DOC', 'DOC'), ('OTHER', 'OTHER')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=30)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotationdestination')),
            ],
        ),
    ]
