# Generated by Django 5.2.5 on 2025-08-25 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_partner_agentproxy_customerproxy_vendorproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volume_cbm', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('extra_notes', models.TextField(blank=True)),
                ('shipper', models.CharField(blank=True, max_length=200)),
                ('consignee', models.CharField(blank=True, max_length=200)),
                ('notify_party', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CargoCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='sales.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('date', models.DateField()),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('transport_mode', models.CharField(choices=[('LAND', 'Land'), ('SEA', 'Sea'), ('AIR', 'Air'), ('MULTI', 'Multi')], default='SEA', max_length=10)),
                ('service_option', models.CharField(blank=True, max_length=30)),
                ('multi_destination', models.BooleanField(default=True)),
                ('destination_header', models.CharField(blank=True, max_length=200)),
                ('origin_header', models.CharField(blank=True, max_length=200)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='partners.partner')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='sales.quotation'),
        ),
    ]
