# Generated by Django 5.2.5 on 2025-08-30 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FreightCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='sales.freightcargo')),
            ],
        ),
        migrations.CreateModel(
            name='FreightQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('transport_mode', models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('LAND', 'Land')], max_length=20)),
                ('service_option', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('multi_destination', models.BooleanField(default=False)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddField(
            model_name='freightcargo',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='sales.freightquotation'),
        ),
    ]
