# Generated by Django 5.2.5 on 2025-08-26 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_partner_agentproxy_customerproxy_vendorproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CargoCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='sales.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('IDR', 'IDR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='IDR', max_length=3)),
                ('business_type', models.CharField(choices=[('FREIGHT', 'Freight'), ('SHIP_CHARTER', 'Ship Charter')], default='FREIGHT', max_length=20)),
                ('transport_mode', models.CharField(default='SEA', max_length=10)),
                ('service_option', models.CharField(default='PORT_TO_PORT', max_length=30)),
                ('multi_destination', models.BooleanField(default=True)),
                ('origin', models.CharField(blank=True, max_length=120)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('charter_type', models.CharField(blank=True, choices=[('VOYAGE', 'Voyage'), ('TIME', 'Time')], max_length=10)),
                ('vessel_name', models.CharField(blank=True, max_length=120)),
                ('vessel_type', models.CharField(blank=True, max_length=120)),
                ('dwt_mt', models.IntegerField(blank=True, null=True)),
                ('laycan_start', models.DateField(blank=True, null=True)),
                ('laycan_end', models.DateField(blank=True, null=True)),
                ('laytime_allowed_hours', models.IntegerField(blank=True, null=True)),
                ('reversible_laytime', models.BooleanField(default=False)),
                ('demurrage_usd_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('despatch_usd_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bunker_terms', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_quotations', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='CharterLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('LOAD', 'Load'), ('DISCH', 'Disch'), ('BUNKER', 'Bunker'), ('PASSAGE', 'Passage')], default='LOAD', max_length=10)),
                ('port', models.CharField(max_length=120)),
                ('terminal', models.CharField(blank=True, max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='sales.quotation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CharterCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charter_charges', to='sales.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='sales.quotation'),
        ),
    ]
