# Generated by Django 5.2.5 on 2025-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='origin',
        ),
        migrations.AddField(
            model_name='quotationline',
            name='origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
