# Generated by Django 5.2.5 on 2025-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_freight_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightquotation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='freightquotation',
            name='origin',
        ),
        migrations.AddField(
            model_name='freightquotation',
            name='payment_term',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
