# Generated by Django 5.2.5 on 2025-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_quotation_origin_quotationline_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationline',
            name='cargo_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='pkg_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='volume_cbm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
