# Generated by Django 5.2.5 on 2025-08-30 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_agentproxy_customerproxy_vendorproxy'),
        ('sales', '0002_remove_freightquotation_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightquotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.partner'),
        ),
    ]
