# Generated by Django 5.2.5 on 2025-08-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quotationline_cargo_name_quotationline_pkg_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='cargo_desc',
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('package_type', models.CharField(blank=True, max_length=50)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volume_cbm', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('extra_notes', models.TextField(blank=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='sales.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='CargoCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('FREIGHT', 'FREIGHT'), ('ORIGIN', 'ORIGIN'), ('DEST', 'DEST'), ('DOC', 'DOC'), ('OTHER', 'OTHER')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='sales.cargo')),
            ],
        ),
        migrations.DeleteModel(
            name='QuotationDestination',
        ),
        migrations.DeleteModel(
            name='QuotationLine',
        ),
    ]
