# Generated by Django 5.2.5 on 2025-08-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('sales', '0003_alter_freightquotation_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightcargo',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_destinations', to='geo.location'),
        ),
        migrations.AlterField(
            model_name='freightcargo',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_origins', to='geo.location'),
        ),
    ]
