# Generated by Django 5.2.5 on 2025-08-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_freightcargo_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightcargo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
