# Generated by Django 5.2.5 on 2025-08-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_quotationline_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='consignee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cargo',
            name='notify_party',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cargo',
            name='shipper',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
