# Generated by Django 5.2.5 on 2025-08-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_freightquotation_price_freightquotation_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightquotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12),
        ),
    ]
