# Generated by Django 5.2.5 on 2025-08-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_freightquotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightquotation',
            name='service_option',
            field=models.CharField(choices=[('DOOR_TO_DOOR', 'Door to door'), ('DOOR_TO_PORT', 'Door to port'), ('PORT_TO_PORT', 'Port to port'), ('DOOR_TO_AIRPORT', 'Door to airport'), ('AIRPORT_TO_AIRPORT', 'Airport to airport'), ('TRUCKING', 'Trucking')], max_length=50),
        ),
    ]
