# Generated by Django 5.2.5 on 2025-09-01 22:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('partners', '0002_partner_agentproxy_customerproxy_vendorproxy'),
        ('sales', '0009_alter_freightquotation_service_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('transport_mode', models.CharField(choices=[('SEA', 'Sea'), ('AIR', 'Air'), ('LAND', 'Land')], max_length=20)),
                ('service_option', models.CharField(choices=[('DOOR_TO_DOOR', 'Door to door'), ('DOOR_TO_PORT', 'Door to port'), ('PORT_TO_PORT', 'Port to port'), ('DOOR_TO_AIRPORT', 'Door to airport'), ('AIRPORT_TO_AIRPORT', 'Airport to airport'), ('TRUCKING', 'Trucking')], max_length=50)),
                ('payment_term', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partners.partner')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='sales.freightquotation')),
            ],
            options={
                'db_table': 'freight_order',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FreightOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_cargo_destinations', to='geo.location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.freightorder')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_cargo_origins', to='geo.location')),
            ],
            options={
                'db_table': 'freight_order_line',
                'ordering': ('id',),
            },
        ),
    ]
